CREATE UNIQUE INDEX idx_230a1cf1$415_deterministic_unique_hash_temp ON summary_transaction_view_temp USING BTREE(duh) WITH (fillfactor = 97);
CREATE INDEX idx_230a1cf1$415_ordered_action_date_temp ON summary_transaction_view_temp USING BTREE(action_date DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_230a1cf1$415_action_date_and_type_temp ON summary_transaction_view_temp USING BTREE(type, action_date DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_230a1cf1$415_type_temp ON summary_transaction_view_temp USING BTREE(type) WITH (fillfactor = 97) WHERE type IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_pulled_from_temp ON summary_transaction_view_temp USING BTREE(pulled_from DESC NULLS LAST) WITH (fillfactor = 97) WHERE pulled_from IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_recipient_unique_id_temp ON summary_transaction_view_temp USING BTREE(recipient_unique_id) WITH (fillfactor = 97);
CREATE INDEX idx_230a1cf1$415_parent_recipient_unique_id_temp ON summary_transaction_view_temp USING BTREE(parent_recipient_unique_id) WITH (fillfactor = 97) WHERE parent_recipient_unique_id IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_recipient_country_code_temp ON summary_transaction_view_temp USING BTREE(recipient_location_country_code) WITH (fillfactor = 97) WHERE recipient_location_country_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_recipient_state_code_temp ON summary_transaction_view_temp USING BTREE(recipient_location_state_code) WITH (fillfactor = 97) WHERE recipient_location_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_recipient_county_code_temp ON summary_transaction_view_temp USING BTREE(recipient_location_county_code) WITH (fillfactor = 97) WHERE recipient_location_county_code IS NOT NULL;
DO $$ BEGIN RAISE NOTICE '10 indexes created, 32 remaining'; END $$;
CREATE INDEX idx_230a1cf1$415_recipient_zip_temp ON summary_transaction_view_temp USING BTREE(recipient_location_zip5) WITH (fillfactor = 97) WHERE recipient_location_zip5 IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_pop_country_code_temp ON summary_transaction_view_temp USING BTREE(pop_country_code) WITH (fillfactor = 97) WHERE pop_country_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_pop_state_code_temp ON summary_transaction_view_temp USING BTREE(pop_state_code) WITH (fillfactor = 97) WHERE pop_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_pop_county_code_temp ON summary_transaction_view_temp USING BTREE(pop_county_code) WITH (fillfactor = 97) WHERE pop_county_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_pop_zip_temp ON summary_transaction_view_temp USING BTREE(pop_zip5) WITH (fillfactor = 97) WHERE pop_zip5 IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_awarding_agency_id_temp ON summary_transaction_view_temp USING BTREE(awarding_agency_id ASC NULLS LAST) WITH (fillfactor = 97) WHERE awarding_agency_id IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_funding_agency_id_temp ON summary_transaction_view_temp USING BTREE(funding_agency_id ASC NULLS LAST) WITH (fillfactor = 97) WHERE funding_agency_id IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_awarding_toptier_agency_name_temp ON summary_transaction_view_temp USING BTREE(awarding_toptier_agency_name) WITH (fillfactor = 97) WHERE awarding_toptier_agency_name IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_awarding_subtier_agency_name_temp ON summary_transaction_view_temp USING BTREE(awarding_subtier_agency_name) WITH (fillfactor = 97) WHERE awarding_subtier_agency_name IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_funding_toptier_agency_name_temp ON summary_transaction_view_temp USING BTREE(funding_toptier_agency_name) WITH (fillfactor = 97) WHERE funding_toptier_agency_name IS NOT NULL;
DO $$ BEGIN RAISE NOTICE '20 indexes created, 22 remaining'; END $$;
CREATE INDEX idx_230a1cf1$415_funding_subtier_agency_name_temp ON summary_transaction_view_temp USING BTREE(funding_subtier_agency_name) WITH (fillfactor = 97) WHERE funding_subtier_agency_name IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_cfda_num_temp ON summary_transaction_view_temp USING BTREE(cfda_number) WITH (fillfactor = 97) WHERE cfda_number IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_cfda_title_temp ON summary_transaction_view_temp USING BTREE(cfda_title) WITH (fillfactor = 97) WHERE cfda_title IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_psc_temp ON summary_transaction_view_temp USING BTREE(product_or_service_code) WITH (fillfactor = 97) WHERE product_or_service_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_naics_temp ON summary_transaction_view_temp USING BTREE(naics_code) WITH (fillfactor = 97) WHERE naics_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_total_obl_bin_temp ON summary_transaction_view_temp USING BTREE(total_obl_bin) WITH (fillfactor = 97) WHERE total_obl_bin IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_type_of_contract_temp ON summary_transaction_view_temp USING BTREE(type_of_contract_pricing) WITH (fillfactor = 97);
CREATE INDEX idx_230a1cf1$415_ordered_action_date_and_set_aside_temp ON summary_transaction_view_temp USING BTREE(action_date DESC NULLS LAST, type_set_aside) WITH (fillfactor = 97);
CREATE INDEX idx_230a1cf1$415_extent_competed_temp ON summary_transaction_view_temp USING BTREE(extent_competed) WITH (fillfactor = 97);
CREATE INDEX idx_230a1cf1$415_type_set_aside_temp ON summary_transaction_view_temp USING BTREE(type_set_aside) WITH (fillfactor = 97) WHERE type_set_aside IS NOT NULL;
DO $$ BEGIN RAISE NOTICE '30 indexes created, 12 remaining'; END $$;
CREATE INDEX idx_230a1cf1$415_business_categories_temp ON summary_transaction_view_temp USING GIN(business_categories);
CREATE INDEX idx_230a1cf1$415_simple_pop_geolocation_temp ON summary_transaction_view_temp USING BTREE(pop_state_code, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_pop_covering_geolocation_temp ON summary_transaction_view_temp USING BTREE(pop_state_code, fiscal_year, generated_pragmatic_obligation, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA';
CREATE INDEX idx_230a1cf1$415_compound_geo_pop_1_temp ON summary_transaction_view_temp USING BTREE(pop_state_code, pop_county_code, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_compound_geo_pop_2_temp ON summary_transaction_view_temp USING BTREE(pop_state_code, pop_congressional_code, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_compound_geo_pop_3_temp ON summary_transaction_view_temp USING BTREE(pop_zip5, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_zip5 IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_simple_recipient_location_geolocation_temp ON summary_transaction_view_temp USING BTREE(recipient_location_state_code, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_recipient_covering_geolocation_temp ON summary_transaction_view_temp USING BTREE(recipient_location_state_code, fiscal_year, generated_pragmatic_obligation, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA';
CREATE INDEX idx_230a1cf1$415_compound_geo_rl_1_temp ON summary_transaction_view_temp USING BTREE(recipient_location_state_code, recipient_location_county_code, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_compound_geo_rl_2_temp ON summary_transaction_view_temp USING BTREE(recipient_location_state_code, recipient_location_congressional_code, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_state_code IS NOT NULL;
DO $$ BEGIN RAISE NOTICE '40 indexes created, 2 remaining'; END $$;
CREATE INDEX idx_230a1cf1$415_compound_geo_rl_3_temp ON summary_transaction_view_temp USING BTREE(recipient_location_zip5, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_zip5 IS NOT NULL;
CREATE INDEX idx_230a1cf1$415_recipient_hash_temp ON summary_transaction_view_temp USING BTREE(recipient_hash) WITH (fillfactor = 97);
