CREATE UNIQUE INDEX idx_230a1cf1$82d_deterministic_unique_hash_temp ON summary_transaction_geo_view_temp USING BTREE(duh) WITH (fillfactor = 97);
CREATE INDEX idx_230a1cf1$82d_date_temp ON summary_transaction_geo_view_temp USING BTREE(action_date DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_230a1cf1$82d_action_date_and_type_temp ON summary_transaction_geo_view_temp USING BTREE(action_date DESC NULLS LAST, type) WITH (fillfactor = 97);
CREATE INDEX idx_230a1cf1$82d_type_temp ON summary_transaction_geo_view_temp USING BTREE(type) WITH (fillfactor = 97) WHERE type IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_pulled_from_temp ON summary_transaction_geo_view_temp USING BTREE(pulled_from DESC NULLS LAST) WITH (fillfactor = 97) WHERE pulled_from IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_recipient_country_code_temp ON summary_transaction_geo_view_temp USING BTREE(recipient_location_country_code) WITH (fillfactor = 97) WHERE recipient_location_country_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_recipient_state_code_temp ON summary_transaction_geo_view_temp USING BTREE(recipient_location_state_code) WITH (fillfactor = 97) WHERE recipient_location_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_recipient_county_code_temp ON summary_transaction_geo_view_temp USING BTREE(recipient_location_county_code) WITH (fillfactor = 97) WHERE recipient_location_county_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_recipient_zip_temp ON summary_transaction_geo_view_temp USING BTREE(recipient_location_zip5) WITH (fillfactor = 97) WHERE recipient_location_zip5 IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_pop_country_code_temp ON summary_transaction_geo_view_temp USING BTREE(pop_country_code) WITH (fillfactor = 97) WHERE pop_country_code IS NOT NULL;
DO $$ BEGIN RAISE NOTICE '10 indexes created, 19 remaining'; END $$;
CREATE INDEX idx_230a1cf1$82d_pop_state_code_temp ON summary_transaction_geo_view_temp USING BTREE(pop_state_code) WITH (fillfactor = 97) WHERE pop_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_pop_county_code_temp ON summary_transaction_geo_view_temp USING BTREE(pop_county_code) WITH (fillfactor = 97) WHERE pop_county_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_pop_zip_temp ON summary_transaction_geo_view_temp USING BTREE(pop_zip5) WITH (fillfactor = 97) WHERE pop_zip5 IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_awarding_agency_id_temp ON summary_transaction_geo_view_temp USING BTREE(awarding_agency_id ASC NULLS LAST) WITH (fillfactor = 97) WHERE awarding_agency_id IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_funding_agency_id_temp ON summary_transaction_geo_view_temp USING BTREE(funding_agency_id ASC NULLS LAST) WITH (fillfactor = 97) WHERE funding_agency_id IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_awarding_toptier_agency_name_temp ON summary_transaction_geo_view_temp USING BTREE(awarding_toptier_agency_name) WITH (fillfactor = 97) WHERE awarding_toptier_agency_name IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_awarding_subtier_agency_name_temp ON summary_transaction_geo_view_temp USING BTREE(awarding_subtier_agency_name) WITH (fillfactor = 97) WHERE awarding_subtier_agency_name IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_funding_toptier_agency_name_temp ON summary_transaction_geo_view_temp USING BTREE(funding_toptier_agency_name) WITH (fillfactor = 97) WHERE funding_toptier_agency_name IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_funding_subtier_agency_name_temp ON summary_transaction_geo_view_temp USING BTREE(funding_subtier_agency_name) WITH (fillfactor = 97) WHERE funding_subtier_agency_name IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_simple_pop_geolocation_temp ON summary_transaction_geo_view_temp USING BTREE(pop_state_code, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_state_code IS NOT NULL;
DO $$ BEGIN RAISE NOTICE '20 indexes created, 9 remaining'; END $$;
CREATE INDEX idx_230a1cf1$82d_pop_covering_geolocation_temp ON summary_transaction_geo_view_temp USING BTREE(pop_state_code, fiscal_year, generated_pragmatic_obligation, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA';
CREATE INDEX idx_230a1cf1$82d_compound_geo_pop_1_temp ON summary_transaction_geo_view_temp USING BTREE(pop_state_code, pop_county_code, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_compound_geo_pop_2_temp ON summary_transaction_geo_view_temp USING BTREE(pop_state_code, pop_congressional_code, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_compound_geo_pop_3_temp ON summary_transaction_geo_view_temp USING BTREE(pop_zip5, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_zip5 IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_simple_recipient_location_geolocation_temp ON summary_transaction_geo_view_temp USING BTREE(recipient_location_state_code, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_recipient_covering_geolocation_temp ON summary_transaction_geo_view_temp USING BTREE(recipient_location_state_code, fiscal_year, generated_pragmatic_obligation, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA';
CREATE INDEX idx_230a1cf1$82d_compound_geo_rl_1_temp ON summary_transaction_geo_view_temp USING BTREE(recipient_location_state_code, recipient_location_county_code, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_compound_geo_rl_2_temp ON summary_transaction_geo_view_temp USING BTREE(recipient_location_state_code, recipient_location_congressional_code, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_state_code IS NOT NULL;
CREATE INDEX idx_230a1cf1$82d_compound_geo_rl_3_temp ON summary_transaction_geo_view_temp USING BTREE(recipient_location_zip5, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_zip5 IS NOT NULL;
