CREATE UNIQUE INDEX idx_76387eb4$b67_id_temp ON universal_award_matview_temp USING BTREE(award_id) WITH (fillfactor = 97);
CREATE INDEX idx_76387eb4$b67_category_temp ON universal_award_matview_temp USING BTREE(category) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_type_temp ON universal_award_matview_temp USING BTREE(type) WITH (fillfactor = 97) WHERE type IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_ordered_type_temp ON universal_award_matview_temp USING BTREE(type DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_ordered_type_desc_temp ON universal_award_matview_temp USING BTREE(type_description DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_ordered_fain_temp ON universal_award_matview_temp USING BTREE(UPPER(fain) DESC NULLS LAST) WITH (fillfactor = 97) WHERE fain IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_ordered_piid_temp ON universal_award_matview_temp USING BTREE(UPPER(piid) DESC NULLS LAST) WITH (fillfactor = 97) WHERE piid IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_total_obligation_temp ON universal_award_matview_temp USING BTREE(total_obligation) WITH (fillfactor = 97) WHERE total_obligation IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_ordered_total_obligation_temp ON universal_award_matview_temp USING BTREE(total_obligation DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_total_obl_bin_temp ON universal_award_matview_temp USING BTREE(total_obl_bin) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
DO $$ BEGIN RAISE NOTICE '10 indexes created, 62 remaining'; END $$;
CREATE INDEX idx_76387eb4$b67_total_subsidy_cost_temp ON universal_award_matview_temp USING BTREE(total_subsidy_cost) WITH (fillfactor = 97) WHERE total_subsidy_cost IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_total_loan_value_temp ON universal_award_matview_temp USING BTREE(total_loan_value) WITH (fillfactor = 97) WHERE total_loan_value IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_ordered_total_subsidy_cost_temp ON universal_award_matview_temp USING BTREE(total_subsidy_cost DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_ordered_total_loan_value_temp ON universal_award_matview_temp USING BTREE(total_loan_value DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_period_of_performance_start_date_temp ON universal_award_matview_temp USING BTREE(period_of_performance_start_date DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_period_of_performance_current_end_date_temp ON universal_award_matview_temp USING BTREE(period_of_performance_current_end_date DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_ordered_ordering_period_end_date_temp ON universal_award_matview_temp USING BTREE(ordering_period_end_date DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_recipient_name_temp ON universal_award_matview_temp USING BTREE(recipient_name) WITH (fillfactor = 97) WHERE recipient_name IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_recipient_unique_id_temp ON universal_award_matview_temp USING BTREE(recipient_unique_id) WITH (fillfactor = 97) WHERE recipient_unique_id IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_parent_recipient_unique_id_temp ON universal_award_matview_temp USING BTREE(parent_recipient_unique_id) WITH (fillfactor = 97) WHERE parent_recipient_unique_id IS NOT NULL AND action_date >= '2007-10-01';
DO $$ BEGIN RAISE NOTICE '20 indexes created, 52 remaining'; END $$;
CREATE INDEX idx_76387eb4$b67_action_date_temp ON universal_award_matview_temp USING BTREE(action_date DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_last_modified_date_temp ON universal_award_matview_temp USING BTREE(last_modified_date DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_76387eb4$b67_awarding_agency_id_temp ON universal_award_matview_temp USING BTREE(awarding_agency_id ASC NULLS LAST) WITH (fillfactor = 97) WHERE awarding_agency_id IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_funding_agency_id_temp ON universal_award_matview_temp USING BTREE(funding_agency_id ASC NULLS LAST) WITH (fillfactor = 97) WHERE funding_agency_id IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_ordered_awarding_toptier_agency_name_temp ON universal_award_matview_temp USING BTREE(awarding_toptier_agency_name DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_ordered_awarding_subtier_agency_name_temp ON universal_award_matview_temp USING BTREE(awarding_subtier_agency_name DESC NULLS LAST) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_awarding_toptier_agency_name_temp ON universal_award_matview_temp USING BTREE(awarding_toptier_agency_name) WITH (fillfactor = 97) WHERE awarding_toptier_agency_name IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_awarding_subtier_agency_name_temp ON universal_award_matview_temp USING BTREE(awarding_subtier_agency_name) WITH (fillfactor = 97) WHERE awarding_subtier_agency_name IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_funding_toptier_agency_name_temp ON universal_award_matview_temp USING BTREE(funding_toptier_agency_name) WITH (fillfactor = 97) WHERE funding_toptier_agency_name IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_funding_subtier_agency_name_temp ON universal_award_matview_temp USING BTREE(funding_subtier_agency_name) WITH (fillfactor = 97) WHERE funding_subtier_agency_name IS NOT NULL AND action_date >= '2007-10-01';
DO $$ BEGIN RAISE NOTICE '30 indexes created, 42 remaining'; END $$;
CREATE INDEX idx_76387eb4$b67_recipient_location_country_code_temp ON universal_award_matview_temp USING BTREE(recipient_location_country_code) WITH (fillfactor = 97) WHERE recipient_location_country_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_recipient_location_state_code_temp ON universal_award_matview_temp USING BTREE(recipient_location_state_code) WITH (fillfactor = 97) WHERE recipient_location_state_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_recipient_location_county_code_temp ON universal_award_matview_temp USING BTREE(recipient_location_county_code) WITH (fillfactor = 97) WHERE recipient_location_county_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_recipient_location_zip5_temp ON universal_award_matview_temp USING BTREE(recipient_location_zip5) WITH (fillfactor = 97) WHERE recipient_location_zip5 IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_recipient_location_cong_code_temp ON universal_award_matview_temp USING BTREE(recipient_location_congressional_code) WITH (fillfactor = 97) WHERE recipient_location_congressional_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_pop_country_code_temp ON universal_award_matview_temp USING BTREE(pop_country_code) WITH (fillfactor = 97) WHERE pop_country_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_pop_state_code_temp ON universal_award_matview_temp USING BTREE(pop_state_code) WITH (fillfactor = 97) WHERE pop_state_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_pop_county_code_temp ON universal_award_matview_temp USING BTREE(pop_county_code) WITH (fillfactor = 97) WHERE pop_county_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_pop_zip5_temp ON universal_award_matview_temp USING BTREE(pop_zip5) WITH (fillfactor = 97) WHERE pop_zip5 IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_pop_congressional_code_temp ON universal_award_matview_temp USING BTREE(pop_congressional_code) WITH (fillfactor = 97) WHERE pop_congressional_code IS NOT NULL AND action_date >= '2007-10-01';
DO $$ BEGIN RAISE NOTICE '40 indexes created, 32 remaining'; END $$;
CREATE INDEX idx_76387eb4$b67_simple_pop_geolocation_temp ON universal_award_matview_temp USING BTREE(pop_state_code, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_state_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_compound_geo_pop_1_temp ON universal_award_matview_temp USING BTREE(pop_state_code, pop_county_code, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_state_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_compound_geo_pop_2_temp ON universal_award_matview_temp USING BTREE(pop_state_code, pop_congressional_code, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_state_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_compound_geo_pop_3_temp ON universal_award_matview_temp USING BTREE(pop_zip5, action_date) WITH (fillfactor = 97) WHERE pop_country_code = 'USA' AND pop_zip5 IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_simple_recipient_location_geolocation_temp ON universal_award_matview_temp USING BTREE(recipient_location_state_code, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_state_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_compound_geo_rl_1_temp ON universal_award_matview_temp USING BTREE(recipient_location_state_code, recipient_location_county_code, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_state_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_compound_geo_rl_2_temp ON universal_award_matview_temp USING BTREE(recipient_location_state_code, recipient_location_congressional_code, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_state_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_compound_geo_rl_3_temp ON universal_award_matview_temp USING BTREE(recipient_location_zip5, action_date) WITH (fillfactor = 97) WHERE recipient_location_country_code = 'USA' AND recipient_location_zip5 IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_cfda_number_temp ON universal_award_matview_temp USING BTREE(cfda_number) WITH (fillfactor = 97) WHERE cfda_number IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_pulled_from_temp ON universal_award_matview_temp USING BTREE(pulled_from) WITH (fillfactor = 97) WHERE pulled_from IS NOT NULL AND action_date >= '2007-10-01';
DO $$ BEGIN RAISE NOTICE '50 indexes created, 22 remaining'; END $$;
CREATE INDEX idx_76387eb4$b67_type_of_contract_pricing_temp ON universal_award_matview_temp USING BTREE(type_of_contract_pricing) WITH (fillfactor = 97) WHERE type_of_contract_pricing IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_extent_competed_temp ON universal_award_matview_temp USING BTREE(extent_competed) WITH (fillfactor = 97) WHERE extent_competed IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_type_set_aside_temp ON universal_award_matview_temp USING BTREE(type_set_aside) WITH (fillfactor = 97) WHERE type_set_aside IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_product_or_service_code_temp ON universal_award_matview_temp USING BTREE(product_or_service_code) WITH (fillfactor = 97) WHERE product_or_service_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_gin_product_or_service_description_temp ON universal_award_matview_temp USING GIN((product_or_service_description) gin_trgm_ops);
CREATE INDEX idx_76387eb4$b67_naics_temp ON universal_award_matview_temp USING BTREE(naics_code) WITH (fillfactor = 97) WHERE naics_code IS NOT NULL AND action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_gin_naics_code_temp ON universal_award_matview_temp USING GIN(naics_code gin_trgm_ops);
CREATE INDEX idx_76387eb4$b67_gin_naics_description_temp ON universal_award_matview_temp USING GIN(UPPER(naics_description) gin_trgm_ops);
CREATE INDEX idx_76387eb4$b67_gin_business_categories_temp ON universal_award_matview_temp USING GIN(business_categories);
CREATE INDEX idx_76387eb4$b67_keyword_ts_vector_temp ON universal_award_matview_temp USING GIN(keyword_ts_vector);
DO $$ BEGIN RAISE NOTICE '60 indexes created, 12 remaining'; END $$;
CREATE INDEX idx_76387eb4$b67_award_ts_vector_temp ON universal_award_matview_temp USING GIN(award_ts_vector);
CREATE INDEX idx_76387eb4$b67_recipient_name_ts_vector_temp ON universal_award_matview_temp USING GIN(recipient_name_ts_vector);
CREATE INDEX idx_76387eb4$b67_compound_psc_action_date_temp ON universal_award_matview_temp USING BTREE(product_or_service_code, action_date) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_compound_naics_action_date_temp ON universal_award_matview_temp USING BTREE(naics_code, action_date) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_compound_cfda_action_date_temp ON universal_award_matview_temp USING BTREE(cfda_number, action_date) WITH (fillfactor = 97) WHERE action_date >= '2007-10-01';
CREATE INDEX idx_76387eb4$b67_awarding_toptier_agency_name_pre2008_temp ON universal_award_matview_temp USING BTREE(awarding_toptier_agency_name) WITH (fillfactor = 97) WHERE awarding_toptier_agency_name IS NOT NULL AND action_date < '2007-10-01';
CREATE INDEX idx_76387eb4$b67_awarding_subtier_agency_name_pre2008_temp ON universal_award_matview_temp USING BTREE(awarding_subtier_agency_name) WITH (fillfactor = 97) WHERE awarding_subtier_agency_name IS NOT NULL AND action_date < '2007-10-01';
CREATE INDEX idx_76387eb4$b67_type_pre2008_temp ON universal_award_matview_temp USING BTREE(type) WITH (fillfactor = 97) WHERE type IS NOT NULL AND action_date < '2007-10-01';
CREATE INDEX idx_76387eb4$b67_pulled_from_pre2008_temp ON universal_award_matview_temp USING BTREE(pulled_from) WITH (fillfactor = 97) WHERE pulled_from IS NOT NULL AND action_date < '2007-10-01';
CREATE INDEX idx_76387eb4$b67_recipient_location_country_code_pre2008_temp ON universal_award_matview_temp USING BTREE(recipient_location_country_code) WITH (fillfactor = 97) WHERE recipient_location_country_code IS NOT NULL AND action_date < '2007-10-01';
DO $$ BEGIN RAISE NOTICE '70 indexes created, 2 remaining'; END $$;
CREATE INDEX idx_76387eb4$b67_recipient_location_state_code_pre2008_temp ON universal_award_matview_temp USING BTREE(recipient_location_state_code) WITH (fillfactor = 97) WHERE recipient_location_state_code IS NOT NULL AND action_date < '2007-10-01';
CREATE INDEX idx_76387eb4$b67_action_date_pre2008_temp ON universal_award_matview_temp USING BTREE(action_date) WITH (fillfactor = 97) WHERE action_date < '2007-10-01';
